branches:
  - main
  - master
tagFormat: 'v${version}'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
        - type: refactor
          release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
